# Feature-to-generator (FG) reconstruction configuration.

defaults:
  - generator: relu7generator

features:
  name: ImageNetTest_bvlc_reference_caffenet
  path: ./data/features/ImageNetTest/bvlc_reference_caffenet

output:
  path: ./data/reconstruction/fg/${_analysis_name_}_${generator.name}/true
  prefix: recon_image-
  ext: tiff

evaluation:
  true_image:
    path: ./data/images/ImageNetTest/source
    ext: JPEG
