# Feature-to-generator (FG) reconstruction configuration.

defaults:
  - paths: default
  - generator: relu6generator

decoded_features:
  name: ImageNetTest_deeprecon_reference_caffenet
  path: ${paths.decoded_features_caffenet}
  subjects:
    - sub-01
  rois:
    - VC
  decoders:
    path: ${paths.feature_decoders_caffenet}

fg:
  feature_scaling: feature_std_train_mean_center

output:
  path: ./data/reconstruction/fg/${_analysis_name_}_${generator.name}_scaling_${fg.feature_scaling}/decoded
  prefix: recon_image-
  ext: tiff

evaluation:
  true_image:
    path: ${paths.true_images}
    ext: JPEG
