# Reconstruction configuration file

defaults:
  - encoder: vgg19
  - generator: relu7generator

decoded_features:
  name: ImageNetTest_deeprecon_VGG19
  path: ./data/decoded_features/ImageNetTest/train_deeprecon_rep5_test_ImageNetTest_fmriprep_pyfastl2lir_alpha100_allunits/caffe/VGG19
  subjects:
    - SA
  rois:
    - VC
  decoders:
    path: ./data/feature_decoders/ImageNetTraining/deeprecon_fmriprep_pyfastl2lir_alpha100_allunits/caffe/VGG19

icnn:
  num_iteration: 1000
  feature_scaling: feature_std_train_mean_center

output:
  path: ./data/reconstruction/icnn/${_analysis_name_}_${encoder.name}_${generator.name}_scaling_${icnn.feature_scaling}_${icnn.num_iteration}iter/decoded/${decoded_features.name}
  prefix: recon_image-
  ext: tiff

evaluation:
  true_image:
    path: /home/nu/data/contents_shared/ImageNetTest/source
    ext: JPEG
