# Reconstruction configuration file

defaults:
  - paths: default
  - encoder: vgg19
  - generator: relu7generator

decoded_features:
  name: ImageNetTest_deeprecon_VGG19
  path: ${paths.decoded_features_vgg19}
  subjects:
    - sub-01
  rois:
    - VC
  decoders:
    path: ${paths.feature_decoders_vgg19}

icnn:
  num_iteration: 1000
  feature_scaling: feature_std_train_mean_center

output:
  path: ./data/reconstruction/icnn/${_analysis_name_}_${encoder.name}_${generator.name}_scaling_${icnn.feature_scaling}_${icnn.num_iteration}iter/decoded/${decoded_features.name}
  prefix: recon_image-
  ext: tiff

evaluation:
  true_image:
    path: ${paths.true_images}
    ext: JPEG
