# @package _group_

name: norm2generator
input_layer: norm2
parameters_file: ${paths.dgn_parameters.norm2}
image_mean_file: ${paths.caffenet_image_mean}
feature_std_file: ${paths.caffenet_feature_std}
latent_shape: [256, 13, 13]
latent_upper_bound_file: ${paths.dgn_act_range.norm2}
latent_upper_bound_shape: [256, 1, 1]
