# @package _group_

name: norm1generator
input_layer: norm1
parameters_file: ${paths.dgn_parameters.norm1}
image_mean_file: ${paths.caffenet_image_mean}
feature_std_file: ${paths.caffenet_feature_std}
latent_shape: [96, 27, 27]
latent_upper_bound_file: ${paths.dgn_act_range.norm1}
latent_upper_bound_shape: [96, 1, 1]
