# @package _group_

name: pool5generator
input_layer: pool5
parameters_file: ${paths.dgn_parameters.pool5}
image_mean_file: ${paths.caffenet_image_mean}
feature_std_file: ${paths.caffenet_feature_std}
latent_shape: [256, 6, 6]
latent_upper_bound_file: ${paths.dgn_act_range.pool5}
latent_upper_bound_shape: [256, 6, 6]
