# @package _group_

name: relu7generator
input_layer: relu7
parameters_file: ${paths.dgn_parameters.relu7}
image_mean_file: ${paths.caffenet_image_mean}
feature_std_file: ${paths.caffenet_feature_std}
latent_shape: [4096]
latent_upper_bound_file: ${paths.dgn_act_range.relu7}
latent_upper_bound_shape: [4096]
