# @package _group_

name: relu6generator
input_layer: relu6
parameters_file: ${paths.dgn_parameters.relu6}
image_mean_file: ${paths.caffenet_image_mean}
feature_std_file: ${paths.caffenet_feature_std}
latent_shape: [4096]
latent_upper_bound_file: ${paths.dgn_act_range.relu6}
latent_upper_bound_shape: [4096]
