# @package _group_

name: relu3generator
input_layer: relu3
parameters_file: ${paths.dgn_parameters.relu3}
image_mean_file: ${paths.caffenet_image_mean}
feature_std_file: ${paths.caffenet_feature_std}
latent_shape: [384, 13, 13]
latent_upper_bound_file: ${paths.dgn_act_range.relu3}
latent_upper_bound_shape: [384, 13, 13]
