# @package _group_

name: relu4generator
input_layer: relu4
parameters_file: ${paths.dgn_parameters.relu4}
image_mean_file: ${paths.caffenet_image_mean}
feature_std_file: ${paths.caffenet_feature_std}
latent_shape: [384, 13, 13]
latent_upper_bound_file: ${paths.dgn_act_range.relu4}
latent_upper_bound_shape: [384, 1, 1]
